# This workflow will do a clean install of npm dependencies,
# build and run dist tests across different versions of node
# For more information see:
# https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: extra npm dist build test on Node.js CI

on:
  push:
    branches: [dev, dev-*, prettierx-*]
  pull_request:
    branches: [dev, dev-*, prettierx-*]

jobs:
  build:
    # ref:
    # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstrategymatrix
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [10.x, 12.x, 8.x]
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i
      - run: npm run build-extra-dist
      - run: npm run test:dist
        env:
          CI: true
