# This workflow will do a clean install of npm dependencies and
# run tests across different versions of node
# (with lint in the end, until replaced by .github/workflows/lint.yml from prettier@2.0.0)
# For more information see:
# https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: npm dev test Node.js CI

on:
  push:
    branches: [dev, dev-*, prettierx-*]
  pull_request:
    branches: [dev, dev-*, prettierx-*]

jobs:
  build:
    # ref:
    # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstrategymatrix
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version:
          - 8.x
          - 10.x
          - 12.x
          - 14.x
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i
      - run: npm test
        env:
          CI: true
      # to be replaced by .github/workflows/lint.yml
      # from prettier@2.0.0:
      # lint from package scripts - should work across prettier@1.x & prettier@2.x:
      - run: npx cross-env EFF_NO_LINK_RULES=true eslint . --format friendly
      # subset of lint:prettier from prettier@2 package scripts:
      - run: npx prettier --check *.md docs/*.md .github/workflows/*.yml
      # equivalent to spellcheck task (lint:spellcheck task from prettier@2):
      - run: npx cspell bin/**/*.js scripts/**/*.js src/**/*.js
      - run: npx cspell docs/**/*.md website/blog/**/*.md changelog_unreleased/**/*.md
